/**
 * strictlybetter — Self-Extract & Installation (OpenCode)
 * =======================================================
 *
 * OpenCode loads npm-installed plugins from its npm cache, which its discovery
 * never scans for skills/agents/commands. So on first run the plugin copies the
 * MODEL-FACING surfaces into OpenCode's config directory, where discovery does
 * look:
 *
 *   skills/    → merged; the whole tree including skills/_shared/ (read at runtime)
 *   agents/    → merged + transformed (Claude frontmatter → mode: subagent,
 *                hidden: true, lowercase tools map with mutating tools denied)
 *   commands/  → generated: /strictlybetter plus /sb-<skill> for the seven others
 *
 * The ENGINE IS NOT EXTRACTED. scripts/sb.py, archetypes/, operators/,
 * templates/, bench/ and tests/fixtures/ stay at the package root and every shell
 * the model runs receives SB_ROOT pointing there (hooks/shell-env.ts), so the
 * skills' resolution waterfall finds the engine that matches the installed
 * version. One copy of the engine, never two.
 *
 * Never clobber the user (omniplugin R8 / pitfall #8): the version file records
 * the sha256 of every file THIS plugin wrote. On a version bump a file is
 * overwritten only when its on-disk hash still equals the hash we wrote —
 * i.e. it is our unmodified copy. A file the user edited, or a file that existed
 * before we did, is preserved and listed in the log. Nothing is ever deleted.
 *
 * Target detection (same as engram's):
 *   directory has opencode.json/jsonc → {directory}/.opencode/     (project-level)
 *   otherwise                          → ~/.config/opencode/       (global)
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync, readdirSync, lstatSync, renameSync } from "node:fs"
import { resolve, join, relative } from "node:path"
import { createHash } from "node:crypto"
import { parseFrontmatter } from "./parse-frontmatter.js"
import { toolMap } from "./agents.js"

export const VERSION_FILE = ".strictlybetter-version.jsonc"

/** Directory categories copied by selfExtract. */
export const DIRS = ["skills", "agents"]

/** The command surface: skill name → command name + description. `/strictlybetter` keeps
 *  its name; the other seven are prefixed `sb-` so generic names (`run`, `status`, `stop`)
 *  cannot collide with a host built-in (omniplugin R5). */
export const COMMANDS_DEF: Record<string, { skill: string; description: string }> = {
  strictlybetter: {
    skill: "strictlybetter",
    description: "strictlybetter front door: orient on this repo, discover metrics, run pre-registered experiments, keep only strictly-better changes",
  },
  "sb-orient": { skill: "orient", description: "strictlybetter: spawn the orienteer and store the project profile" },
  "sb-metrics": { skill: "metrics", description: "strictlybetter: discover metric cards, measure sigma, probe monotonicity" },
  "sb-run": { skill: "run", description: "strictlybetter: run exactly one research-loop cycle (prereg, experiment, judge, confirm, accept or discard)" },
  "sb-status": { skill: "status", description: "strictlybetter: campaign status, cold-start brief, budget counters, quoted from the engine" },
  "sb-distill": { skill: "distill", description: "strictlybetter: distill the ledger into the inheritance body" },
  "sb-stop": { skill: "stop", description: "strictlybetter: stop the loop at the next safe point (writes the STOP file)" },
  "sb-bench": { skill: "bench", description: "strictlybetter: run the meta-benchmark (walled loop vs naive) on fixture repos" },
}

const GENERATED_MARK = "<!-- generated by strictlybetter; regenerated on every extract, do not edit -->"

/** Extracts the version string from package.json. Falls back to "0.0.0". */
export function getVERSION(root: string): string {
  try {
    const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf-8"))
    return pkg.version || "0.0.0"
  } catch {
    return "0.0.0"
  }
}

/** Returns project-level .opencode/ if the directory has opencode.json(c), else global ~/.config/opencode/. */
export function getExtractTarget(directory: string): string {
  const home = process.env.HOME || process.env.USERPROFILE || "/tmp"
  if (existsSync(resolve(directory, "opencode.json")) || existsSync(resolve(directory, "opencode.jsonc"))) {
    return resolve(directory, ".opencode")
  }
  return resolve(home, ".config", "opencode")
}

export interface VersionRecord {
  version?: string
  previous?: string
  installed_at?: string
  source?: string
  files?: Record<string, string>
}

/** Reads the version file. Returns {} when missing or corrupt. */
export function readVersionRecord(target: string): VersionRecord {
  const f = resolve(target, VERSION_FILE)
  if (!existsSync(f)) return {}
  try {
    const v = JSON.parse(readFileSync(f, "utf-8"))
    return v && typeof v === "object" ? v : {}
  } catch {
    return {}
  }
}

export function sha256(content: string | Buffer): string {
  return createHash("sha256").update(content).digest("hex")
}

/** Converts a Claude Code agent markdown to OpenCode YAML format. Idempotent. */
export function transformAgentForOpenCode(content: string): string {
  const { attrs, body } = parseFrontmatter(content)
  if (attrs.mode === "subagent") return content
  const lines: string[] = []
  if (attrs.name) lines.push(`name: ${attrs.name}`)
  if (attrs.description) lines.push(`description: ${JSON.stringify(attrs.description)}`)
  lines.push("mode: subagent", "hidden: true", "tools:")
  for (const [tool, on] of Object.entries(toolMap(attrs.tools))) lines.push(`  ${tool}: ${on}`)
  return `---\n${lines.join("\n")}\n---\n\n${body.trimEnd()}\n`
}

/** Recursively lists files under dir as paths relative to dir. Symlinks are skipped. */
function walk(dir: string, base = dir, out: string[] = []): string[] {
  if (!existsSync(dir)) return out
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name)
    if (entry.isSymbolicLink()) continue
    if (entry.isDirectory()) walk(p, base, out)
    else if (entry.isFile()) out.push(relative(base, p))
  }
  return out
}

export interface ExtractReport {
  written: string[]
  preserved: string[]
}

/**
 * Copies one category. `owned` is the previous version file's hash map (what we wrote
 * last time); `files` receives the hashes of what we write now. A destination that is
 * a symlink is never written through (a dotfiles manager may have planted it).
 */
export function extractCategory(
  src: string,
  dest: string,
  owned: Record<string, string>,
  files: Record<string, string>,
  transform: ((content: string) => string) | undefined,
  report: ExtractReport,
) {
  for (const rel of walk(src)) {
    const key = `${relative(resolve(src, ".."), src)}/${rel}`.split("\\").join("/")
    let content = readFileSync(join(src, rel), "utf-8")
    if (transform && rel.endsWith(".md")) content = transform(content)
    const hash = sha256(content)
    const target = join(dest, rel)
    if (existsSync(target)) {
      try { if (lstatSync(target).isSymbolicLink()) { report.preserved.push(key); continue } } catch { continue }
      const existing = sha256(readFileSync(target))
      if (existing === hash) { files[key] = hash; continue }          // identical already
      if (owned[key] && owned[key] === existing) {                     // our unmodified copy → refresh
        writeFileSync(target, content)
        files[key] = hash
        report.written.push(key)
        continue
      }
      if (owned[key]) files[key] = owned[key]                         // user-modified: remember what WE wrote
      report.preserved.push(key)
      continue
    }
    mkdirSync(resolve(target, ".."), { recursive: true })
    writeFileSync(target, content)
    files[key] = hash
    report.written.push(key)
  }
}

/** Writes commands/<name>.md for every entry in COMMANDS_DEF. Overwrites only files it generated. */
export function generateCommands(target: string, log: (msg: string) => void) {
  const commandsDir = resolve(target, "commands")
  mkdirSync(commandsDir, { recursive: true })
  for (const [name, def] of Object.entries(COMMANDS_DEF)) {
    const content = `---\ndescription: ${JSON.stringify(def.description)}\n---\n\n${GENERATED_MARK}\n\n# /${name}\n\nLOAD AND FOLLOW the \`${def.skill}\` skill (use the skill tool; its SKILL.md is the whole procedure). Run its engine-resolution block VERBATIM first — \`SB_ROOT\` is exported into every shell by the plugin — and quote the engine's output; never compute a statistic yourself.\n\nArguments: $ARGUMENTS\n`
    const file = resolve(commandsDir, `${name}.md`)
    if (existsSync(file)) {
      try { if (lstatSync(file).isSymbolicLink()) continue } catch { continue }
      const body = readFileSync(file, "utf-8")
      if (body === content) continue
      if (!body.includes(GENERATED_MARK)) continue   // the user's own command with this name: never touched
    }
    writeFileSync(file, content)
  }
  log(`strictlybetter: generated commands in ${commandsDir}`)
}

/**
 * Main extraction entry point. Idempotent via the version file.
 *
 * @returns target path, whether this was a fresh install, previous version, report
 */
export function selfExtract(
  packageRoot: string,
  directory: string,
  version: string,
  logger?: (msg: string) => void,
): { target: string; freshlyExtracted: boolean; prevVersion?: string; report?: ExtractReport } {
  const target = getExtractTarget(directory)
  const prev = readVersionRecord(target)
  const prevVersion = prev.version
  if (prevVersion === version) return { target, freshlyExtracted: false }

  const log = logger || (() => {})
  try {
    const owned = prev.files || {}
    const files: Record<string, string> = {}
    const report: ExtractReport = { written: [], preserved: [] }
    for (const dir of DIRS) {
      const src = resolve(packageRoot, dir)
      if (!existsSync(src)) continue
      const transform = dir === "agents" ? transformAgentForOpenCode : undefined
      extractCategory(src, resolve(target, dir), owned, files, transform, report)
      log(`strictlybetter: merged ${dir} into ${resolve(target, dir)}`)
    }
    generateCommands(target, log)
    if (report.preserved.length) {
      log(`strictlybetter: WARNING — ${report.preserved.length} file(s) preserved because you edited them (or they predate this plugin); the shipped versions were not applied: ${report.preserved.join(", ")}`)
    }

    // Atomic: a torn version file would downgrade the next start to a fresh install
    // that no longer knows which files it owns.
    mkdirSync(target, { recursive: true })
    const versionFile = resolve(target, VERSION_FILE)
    const tmp = versionFile + ".tmp"
    writeFileSync(tmp, JSON.stringify({
      version,
      previous: prevVersion || undefined,
      installed_at: new Date().toISOString(),
      source: "npm",
      files,
    }, null, 2))
    renameSync(tmp, versionFile)
    return { target, freshlyExtracted: !prevVersion, prevVersion, report }
  } catch (e) {
    log(`strictlybetter: extract failed — ${String(e)}`)
    return { target, freshlyExtracted: false }
  }
}
